---
# build-servers.yml
- hosts: 10.10.20.20
  #Define user and password variables
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("guest123", "guest")'
    password : cisco123
    user : devbox
  roles:
    - users
    - common
    - docker
    - node
    - python
    - drone-cli
    - pycharm
